name: Deploy Facebook Bot

# تحديد الأحداث التي تشغل هذا الإجراء
on:
  push:
    branches:
      - main  # سيعمل فقط عند الدفع إلى الفرع الرئيسي

jobs:
  build:
    runs-on: ubuntu-latest  # البيئة التي سيتم بناء المشروع عليها

    steps:
      # 1. استيراد المستودع من GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. إعداد بيئة Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # تحديد إصدار Python المطلوب

      # 3. تثبيت الحزم المطلوبة باستخدام pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # تثبيت الحزم من ملف requirements.txt
          pip install chromedriver-autoinstaller  # تثبيت مكتبة chromedriver-autoinstaller إذا كنت بحاجة إليها

      # 4. تشغيل السكربت
      - name: Run bot
        run: |
          python bot.py  # تشغيل السكربت bot.py
